kind: Template
apiVersion: v1
metadata:
  annotations:
    tags: nfs-auto-provisioner
  name: nfs-auto-provisioner
objects:
- kind: Namespace
  apiVersion: v1
  metadata:
    name: "${NAMESPACE_NFS}"
- kind: ServiceAccount
  apiVersion: v1
  metadata:
    name: nfs-client-provisioner
    namespace: "${NAMESPACE_NFS}"
- kind: ClusterRole
  apiVersion: rbac.authorization.k8s.io/v1
  metadata:
    name: nfs-client-provisioner-runner
  rules:
    - apiGroups: [""]
      resources: ["persistentvolumes"]
      verbs: ["get", "list", "watch", "create", "delete"]
    - apiGroups: [""]
      resources: ["persistentvolumeclaims"]
      verbs: ["get", "list", "watch", "update"]
    - apiGroups: ["storage.k8s.io"]
      resources: ["storageclasses"]
      verbs: ["get", "list", "watch"]
    - apiGroups: [""]
      resources: ["events"]
      verbs: ["create", "update", "patch"]
- kind: ClusterRoleBinding
  apiVersion: rbac.authorization.k8s.io/v1
  metadata:
    name: run-nfs-client-provisioner
  subjects:
    - kind: ServiceAccount
      name: nfs-client-provisioner
      namespace: "${NAMESPACE_NFS}"
  roleRef:
    kind: ClusterRole
    name: nfs-client-provisioner-runner
    apiGroup: rbac.authorization.k8s.io
- kind: Role
  apiVersion: rbac.authorization.k8s.io/v1
  metadata:
    name: leader-locking-nfs-client-provisioner
    namespace: "${NAMESPACE_NFS}"
  rules:
    - apiGroups: [""]
      resources: ["endpoints"]
      verbs: ["get", "list", "watch", "create", "update", "patch"]
- kind: RoleBinding
  apiVersion: rbac.authorization.k8s.io/v1
  metadata:
    name: leader-locking-nfs-client-provisioner
    namespace: "${NAMESPACE_NFS}"
  subjects:
    - kind: ServiceAccount
      name: nfs-client-provisioner
  roleRef:
    kind: Role
    name: leader-locking-nfs-client-provisioner
    apiGroup: rbac.authorization.k8s.io
- kind: Deployment
  apiVersion: apps/v1
  metadata:
    name: nfs-client-provisioner
    namespace: "${NAMESPACE_NFS}"
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: nfs-client-provisioner
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          app: nfs-client-provisioner
      spec:
        serviceAccountName: nfs-client-provisioner
        containers:
          - name: nfs-client-provisioner
            #image: quay.io/external_storage/nfs-client-provisioner:latest
            image: gcr.io/k8s-staging-sig-storage/nfs-subdir-external-provisioner:v4.0.2
            volumeMounts:
              - name: nfs-client-root
                mountPath: /persistentvolumes
            env:
              - name: PROVISIONER_NAME
                value: k8s-sigs.io/nfs-subdir-external-provisioner
              - name: NFS_SERVER
                value: "${NFS_SERVER}"
              - name: NFS_PATH
                value: "${NFS_PATH}"
        volumes:
          - name: nfs-client-root
            nfs:
              server: "${NFS_SERVER}"
              path: "${NFS_PATH}"
- kind: StorageClass
  apiVersion: storage.k8s.io/v1
  metadata:
    name: managed-nfs-storage
    annotations:
      storageclass.kubernetes.io/is-default-class: "true"
  provisioner: "k8s-sigs.io/nfs-subdir-external-provisioner"
  parameters:
    archiveOnDelete: "false"
    pathPattern: "${.PVC.namespace}/${.PVC.name}/${.PVC.annotations.nfs.io/storage-path}" # waits for nfs.io/storage-path annotation, if not specified will accept as empty string.
    onDelete: delete
parameters:
  - name: NFS_SERVER
    displayName: NFS Server IP
    description: IP of the NFS server
    required: true
  - name: NFS_PATH
    displayName: NFS Path
    description: Path on the NFS server
    required: true
  - name: NAMESPACE_NFS
    displayName: Namespace for NFS
    description: Namespace for NFS
    required: true
    value: "nfs-client-provisioner"
  - name: PROVISIONER_NAME
    displayName: Provisioner Meta Name for NFS
    description: Provisioner Meta Name for NFS
    required: true
    value: "k8s-sigs.io/nfs-subdir-external-provisioner"
