---
- name: Deploy Services
  hosts: all

  vars:
    # =============================================================
    use_site_configs: false
    site_config_name: "{{ inventory_hostname }}"

    container_root_dir: /opt/caas

    podman_bridge_name: bridge0

    app_wildcard_base: apps.kemo.labs

    # for pulling from Github Container Registry
    #ghcr_pull_auth_file: /opt/ghcr.io.json

    # =============================================================
    # Database Services
    deploy_db_services: false
    #db_service_ip_address: 192.168.42.14
    #pgsql_db_container_image: docker-ptc.jfrog.lab.kemo.network/postgres:17-alpine
    #mysql_db_container_image: docker-ptc.jfrog.lab.kemo.network/mariadb:11-ubi
    #adminer_container_image: docker-ptc.jfrog.lab.kemo.network/adminer:latest

    # =============================================================
    # Pihole
    deploy_pihole: false
    #pihole_ip_address: 192.168.42.12
    #pihole_container_image: docker-ptc.jfrog.lab.kemo.network/pihole/pihole:latest
    #pihole_admin_password: notpassword
    #pihole_admin_email: ken@kenmoini.com
    pihole_timezone: America/New_York
    pihole_upstream_dns_servers:
      - 208.67.220.220
      - 208.67.222.222
    pihole_temperature_unit: f

    # =============================================================
    # PowerDNS
    deploy_pdns: false
    #pdns_ip_address: 192.168.42.11
    #pdns_auth_image: quay-ptc.jfrog.lab.kemo.network/kenmoini/pdns-auth:latest
    #pdns_recursor_image: quay-ptc.jfrog.lab.kemo.network/kenmoini/pdns-recursor:latest
    #pdns_db_image: ghcr.io/kenmoini/lab-powerdns:mysql-latest
    #pdns_ui_image: docker-ptc.jfrog.lab.kemo.network/powerdnsadmin/pda-legacy:latest

    #pdns_enable_db: false
    #pdns_mysql_host: 192.168.42.14 # db.kemo.labs
    #pdns_mysql_db: pdnsadmin

    # pdns_upstream_servers:
    #   - 192.168.42.12

    # pdns_forward_zones:
    #   - name: kemo.labs
    #     server: "{{ pdns_ip_address }}:5300"
    #   - name: kemo.network
    #     server: "{{ pdns_ip_address }}:5300"
    #   - name: kemo.edge
    #     server: "192.168.99.2:53"

    # =============================================================
    # Chronyd - needs host network access
    deploy_chronyd: false
    # chronyd_container_image: docker-ptc.jfrog.lab.kemo.network/publicarray/chrony:latest
    #chronyd_servers:
    #  - 192.168.42.61
    #  - 192.168.42.62
    #  - 192.168.42.63

    # =============================================================
    # Squid Proxy
    deploy_squid: false
    # squid_ip_address: 192.168.42.18
    # squid_hostname: proxy.kemo.labs
    # squid_container_image: quay-ptc.jfrog.lab.kemo.network/kenmoini/squid-proxy:latest

    # =============================================================
    # JFrog Artifactory
    # Need to provide it a hostname, IP, additional wildcard subdomain, and SSL certs
    deploy_jfrog: false
    # jfrog_ip_address: 192.168.42.32
    # jfrog_hostname: jfrog.lab.kemo.network
    #haproxy_container_image: docker-ptc.jfrog.lab.kemo.network/library/haproxy:latest

    # =============================================================
    # NGINX Proxy Manager
    deploy_nginxpm: false
    #npm_ip_address: 192.168.42.25
    #npm_container_image: docker-ptc.jfrog.lab.kemo.network/jc21/nginx-proxy-manager:latest
    #db_container_image: docker-ptc.jfrog.lab.kemo.network/postgres:latest
    #npm_enable_db: false
    #npm_db_host: db.kemo.labs
    #npm_db_password: n0tNGINXProxyManager
    #npm_db_username: nginxpm
    #npm_db_name: nginxpm

    # =============================================================
    # Shared Pod Setup
    deploy_shared_pod: false
    shared_pod_ip_address: 192.168.42.16

    # =============================================================
    # Shared Pod - Dropbox
    deploy_shared_dropbox: false
    #dropbox_container_image: docker-ptc.jfrog.lab.kemo.network/nginx:latest

    # =============================================================
    # Shared Pod - Vault
    deploy_shared_vault: false
    vault_ip_address: "{{ shared_pod_ip_address }}"
    #vault_container_image: docker-ptc.jfrog.lab.kemo.network/hashicorp/vault:latest

    # =============================================================
    # Shared Pod - Homepage
    deploy_shared_homepage: false

    # =============================================================
    # Netbox
    # Create user with podman exec -it lab-netbox-netbox /opt/netbox/netbox/manage.py createsuperuser
    deploy_netbox: false
    # netbox_ip_address: 192.168.42.22
    # netbox_container_image: quay-ptc.jfrog.lab.kemo.network/netboxcommunity/netbox:latest
    # netbox_db_container_image: docker-ptc.jfrog.lab.kemo.network/postgres:17-alpine
    # netbox_redis_container_image: docker-ptc.jfrog.lab.kemo.network/valkey/valkey:8.0-alpine
    # netbox_cache_container_image: docker-ptc.jfrog.lab.kemo.network/valkey/valkey:8.0-alpine
    # netbox_enable_db: false
    # netbox_db_host: db.kemo.labs
    # netbox_db_password: n0tNetBox

    # =============================================================
    # StepCA
    deploy_shared_stepca: false
    #stepca_container_image: docker-ptc.jfrog.lab.kemo.network/smallstep/step-ca:latest

    # =============================================================
    # FreeIPA
    deploy_freeipa: false
    freeipa_ip_address: 192.168.42.13
    freeipa_hostname: idm.kemo.labs
    #freeipa_container_image: quay-ptc.jfrog.lab.kemo.network/freeipa/freeipa-server:fedora-41

    # =============================================================
    # Keycloak
    deploy_shared_keycloak: false
    #keycloak_db_container_image: docker-ptc.jfrog.lab.kemo.network/postgres:latest

    # =============================================================
    # Observability
    deploy_o11y: false
    # o11y_ip_address: 192.168.42.23
    # o11y_grafana_container_image: docker-ptc.jfrog.lab.kemo.network/bitnami/grafana:latest
    # o11y_grafana_image_container_image: docker-ptc.jfrog.lab.kemo.network/bitnami/grafana-image-renderer:latest
    # o11y_grafana_db_container_image: docker-ptc.jfrog.lab.kemo.network/postgres:17-alpine
    # o11y_alertmanager_container_image: quay-ptc.jfrog.lab.kemo.network/prometheus/alertmanager:latest
    # o11y_prometheus_container_image: quay-ptc.jfrog.lab.kemo.network/prometheus/prometheus:latest
    # o11y_node_exporter_container_image: quay-ptc.jfrog.lab.kemo.network/prometheus/node-exporter:latest

    # o11y_enable_db: false
    # o11y_db_host: db.kemo.labs
    # o11y_db_username: grafana
    # o11y_db_password: n0tGraf4n4
    # o11y_db_name: grafana

    # =============================================================
    # OpenObserve
    deploy_shared_openobserve: false

    # =============================================================
    # Shared Pod - Lego Bridge
    deploy_shared_lego_bridge: false
    # legobridge_container_image: quay-ptc.jfrog.lab.kemo.network/kenmoini/lego-bridge:latest

    # =============================================================
    # Shared DB PGSQL - Change to shared DB services (Adminer, MySQL, PGSQL)
    #deploy_shared_db_pgsql: false
    #pgadmin_container_image: docker-ptc.jfrog.lab.kemo.network/dpage/pgadmin4:latest
    #pgsql_db_container_image: docker-ptc.jfrog.lab.kemo.network/postgres:17-alpine

    # =============================================================
    # Media Services
    deploy_media_services: false
    ms_ip_address: 192.168.42.20
    ms_tv_path: /mnt/Media/TVShows
    ms_movie_path: /mnt/Media/Movies
    ms_music_path: /mnt/Media/Music
    ms_sabnzbd_downloads_path: /mnt/Media/sabnzbd/complete
    ms_sabnzbd_incomplete_path: /mnt/Media/sabnzbd/incomplete

    # =============================================================
    # Roon Server
    # Doesn't work with homeassistant?!?!?!?!?
    deploy_roon: false

    # =============================================================
    # Shared Pod - Gitea
    deploy_shared_gitea: false
    gitea_hostname: "gitea.{{ app_wildcard_base }}"
    gitea_protocol: https
    gitea_enable_db: false
    gitea_db_host: db.kemo.labs
    gitea_db_password: n0tGitea

    # =============================================================
    # Shared Pod - iPerf3
    deploy_shared_iperf3: false
    #iperf3_container_image: docker-ptc.jfrog.lab.kemo.network/networkstatic/iperf3:latest

    # =============================================================
    # Shared Pod - Sushy Tools
    deploy_shared_sushy_tools: false

  # ===============================================================
  tasks:

    - name: SITECONFIG - Read in site configs
      when:
        - use_site_configs | bool
        - site_config_name is defined
      ansible.builtin.include_vars:
        dir: "site-config/{{ site_config_name }}"
        extensions:
          - 'yaml'
          - 'yml'
      tags:
        - always

    - name: Create Service Containers Directory
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: root
        group: root
      with_items:
        - "{{ container_root_dir }}"

    - name: Deploy Database Services
      when: deploy_db_services|bool
      ansible.builtin.include_role:
        name: db

    - name: Deploy PiHole
      when: deploy_pihole|bool
      ansible.builtin.include_role:
        name: pihole

    - name: Deploy Chronyd
      when: deploy_chronyd|bool
      ansible.builtin.include_role:
        name: chronyd

    - name: Deploy PowerDNS
      when: deploy_pdns|bool
      ansible.builtin.include_role:
        name: powerdns

    - name: Deploy Squid Outbound Proxy
      when: deploy_squid|bool
      ansible.builtin.include_role:
        name: squid

    - name: Deploy Shared Pod Setup
      when: deploy_shared_pod|bool
      ansible.builtin.include_role:
        name: shared_pod_setup

    - name: Deploy Shared Pod - Dropbox
      when: deploy_shared_dropbox|bool
      ansible.builtin.include_role:
        name: shared_dropbox

    - name: Deploy Shared Pod - Vault
      when: deploy_shared_vault|bool
      ansible.builtin.include_role:
        name: shared_pod_vault

    - name: Deploy Shared Pod - Homepage
      when: deploy_shared_homepage|bool
      ansible.builtin.include_role:
        name: shared_pod_homepage

    - name: Deploy JFrog Artifactory
      when: deploy_jfrog|bool
      ansible.builtin.include_role:
        name: jfrog

    - name: Deploy NGINX Proxy Manager
      when: deploy_nginxpm|bool
      ansible.builtin.include_role:
        name: nginxpm

    - name: Deploy Netbox
      when: deploy_netbox|bool
      ansible.builtin.include_role:
        name: netbox

    - name: Deploy StepCA
      when: deploy_shared_stepca|bool
      ansible.builtin.include_role:
        name: shared_pod_stepca

    - name: Deploy Observability
      when: deploy_o11y|bool
      ansible.builtin.include_role:
        name: o11y

    - name: Deploy FreeIPA
      when: deploy_freeipa|bool
      ansible.builtin.include_role:
        name: freeipa

    - name: Deploy Shared Keycloak
      when: deploy_shared_keycloak|bool
      ansible.builtin.include_role:
        name: shared_pod_keycloak

    - name: Deploy Shared Pod - OpenObserve
      when: deploy_shared_openobserve|bool
      ansible.builtin.include_role:
        name: shared_pod_openobserve

    #- name: Deploy Shared DB PGSQL
    #  when: deploy_shared_db_pgsql|bool
    #  ansible.builtin.include_role:
    #    name: shared_db_pgsql

    - name: Deploy Shared Pod - Lego Bridge
      when: deploy_shared_lego_bridge|bool
      ansible.builtin.include_role:
        name: shared_pod_lego_bridge

    - name: Deploy Media Services
      when: deploy_media_services|bool
      ansible.builtin.include_role:
        name: media_services

    - name: Deploy Roon Server
      when: deploy_roon|bool
      ansible.builtin.include_role:
        name: roon
      vars:
        # Roon needs either host networking or to be stuffed in a VM cause it needs any/multi/unicast
        podman_bridge_name: host

    - name: Deploy Shared Pod - Gitea
      when: deploy_shared_gitea|bool
      ansible.builtin.include_role:
        name: shared_pod_gitea

    - name: Deploy Shared Pod - iPerf3
      when: deploy_shared_iperf3|bool
      ansible.builtin.include_role:
        name: shared_pod_iperf3

    - name: Deploy Shared Pod - Sushy Tools
      when: deploy_shared_sushy_tools|bool
      ansible.builtin.include_role:
        name: shared_pod_sushy