---
- name: Deploy Services
  hosts: labcore

  vars:
    container_root_dir: /opt/caas

    podman_bridge_name: bridge0

    ghcr_pull_auth_file: /opt/ghcr.io.json

    # =============================================================
    # Pihole
    deploy_pihole: false
    pihole_ip_address: 192.168.42.12
    pihole_admin_password: notpassword
    pihole_timezone: America/New_York
    pihole_admin_email: ken@kenmoini.com
    pihole_upstream_dns_servers:
      - 208.67.220.220
      - 208.67.222.222
    pihole_temperature_unit: f

    # =============================================================
    # PowerDNS
    deploy_pdns: false
    pdns_ip_address: 192.168.42.11

    pdns_upstream_servers:
      - 192.168.42.12

    pdns_forward_zones:
      - name: kemo.labs
        server: "{{ pdns_ip_address }}:5300"
      - name: kemo.network
        server: "{{ pdns_ip_address }}:5300"
      - name: kemo.edge
        server: "192.168.99.2:53"

    # =============================================================
    # Chronyd - needs host network access
    deploy_chronyd: false
    #chronyd_servers:
    #  - 192.168.42.61
    #  - 192.168.42.62
    #  - 192.168.42.63

    # =============================================================
    # Squid Proxy
    deploy_squid: false
    squid_ip_address: 192.168.42.18
    squid_hostname: proxy.kemo.labs

    # =============================================================
    # JFrog Artifactory
    # Need to provide it a hostname, IP, additional wildcard subdomain, and SSL certs
    deploy_jfrog: false
    jfrog_ip_address: 192.168.42.32
    jfrog_hostname: jfrog.lab.kemo.network

    # =============================================================
    # NGINX Proxy Manager
    deploy_nginxpm: false
    npm_ip_address: 192.168.42.25

    # =============================================================
    # Shared Pod Setup
    deploy_shared_pod: false
    shared_pod_ip_address: 192.168.42.16

    # =============================================================
    # Shared Pod - Dropbox
    deploy_shared_dropbox: false

    # =============================================================
    # Shared Pod - Vault
    deploy_shared_vault: false
    vault_ip_address: "{{ shared_pod_ip_address }}"

    # =============================================================
    # Shared Pod - Homepage
    deploy_shared_homepage: false

    # =============================================================
    # Netbox
    # Create user with podman exec -it lab-netbox-netbox /opt/netbox/netbox/manage.py createsuperuser
    deploy_netbox: false
    netbox_ip_address: 192.168.42.22

    # =============================================================
    # StepCA
    deploy_shared_stepca: false

    # =============================================================
    # FreeIPA
    deploy_freeipa: false
    freeipa_ip_address: 192.168.42.13
    freeipa_hostname: idm.kemo.labs

    # =============================================================
    # Observability
    deploy_o11y: false
    o11y_ip_address: 192.168.42.23

    # =============================================================
    # OpenObserve
    deploy_shared_openobserve: true

  # ===============================================================
  tasks:
    - name: Create Service Containers Directory
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: root
        group: root
      with_items:
        - "{{ container_root_dir }}"

    - name: Deploy PiHole
      when: deploy_pihole|bool
      ansible.builtin.include_role:
        name: pihole

    - name: Deploy Chronyd
      when: deploy_chronyd|bool
      ansible.builtin.include_role:
        name: chronyd

    - name: Deploy PowerDNS
      when: deploy_pdns|bool
      ansible.builtin.include_role:
        name: powerdns

    - name: Deploy Squid Outbound Proxy
      when: deploy_squid|bool
      ansible.builtin.include_role:
        name: squid

    - name: Deploy Shared Pod Setup
      when: deploy_shared_pod|bool
      ansible.builtin.include_role:
        name: shared_pod_setup

    - name: Deploy Shared Pod - Dropbox
      when: deploy_shared_dropbox|bool
      ansible.builtin.include_role:
        name: shared_dropbox

    - name: Deploy Shared Pod - Vault
      when: deploy_shared_vault|bool
      ansible.builtin.include_role:
        name: shared_pod_vault

    - name: Deploy Shared Pod - Homepage
      when: deploy_shared_homepage|bool
      ansible.builtin.include_role:
        name: shared_pod_homepage

    - name: Deploy JFrog Artifactory
      when: deploy_jfrog|bool
      ansible.builtin.include_role:
        name: jfrog

    - name: Deploy NGINX Proxy Manager
      when: deploy_nginxpm|bool
      ansible.builtin.include_role:
        name: nginxpm

    - name: Deploy Netbox
      when: deploy_netbox|bool
      ansible.builtin.include_role:
        name: netbox

    - name: Deploy StepCA
      when: deploy_shared_stepca|bool
      ansible.builtin.include_role:
        name: shared_pod_stepca

    - name: Deploy Observability
      when: deploy_o11y|bool
      ansible.builtin.include_role:
        name: o11y

    - name: Deploy FreeIPA
      when: deploy_freeipa|bool
      ansible.builtin.include_role:
        name: freeipa

    - name: Deploy Shared Pod - OpenObserve
      when: deploy_shared_openobserve|bool
      ansible.builtin.include_role:
        name: shared_pod_openobserve