---
# defaults file for shared_pod_lego_bridge

shared_pod_name: shared-pod

legobridge_service_name: legobridge

legobridge_container_image: quay.io/kenmoini/lego-bridge:latest

legobridge_container_port: 3100

# This is defaulted to false since the container isn't UBI based and there needs to be some careful mapping done
legobridge_mount_host_trusted_certs: true

legobridge_pdns_api_key: supersecretapikey
legobridge_pdns_api_uri: http://ns1.kemo.labs:8081
legobridge_acme_server_url: "https://step-ca.{{ app_wildcard_base }}/acme/acme/directory"
legobridge_acme_email: ken@kenmoini.com
legobridge_dns_servers:
  - 192.168.42.11