---

set_hostname: false
add_root_ca_certs: false

configured_roles:
- update-system # optional reboot if kernel is updated
- install-base-packages
- general-config
- configure-cockpit
- configure-ntp
- configure-sshd
- podman-host
- setup-ipa-client # optional reboot if newly joined to domain
- configure-firewall