---
reboot_after_default_zone_change: true

firewall:
  enabled: true
  at_boot: true

  zones:
  - name: public
    description: Remove the old default zone if it exists
    state: absent

  - name: lab
    description: A zone for the lab that I tightly maintain
    state: present
    default: true
    enable_forwarding: true
    #enable_masquerading: true

    block_ping: false
    # target: ACCEPT | DROP | REJECT or just omit for default
    target: ACCEPT
    
    allowed_services:
    - ssh
    - http
    - https
    - cockpit
    - dhcpv6-client
    - mdns
    - samba-client

    allowed_ports:
    - port: 8080
      protocol: tcp
    - port: 8081
      protocol: tcp
    - port: 8082
      protocol: tcp

    allowed_sources:
    - 0.0.0.0/0

    interfaces:
    - bridge0

  # ubuntu-based systems use profiles instead of zones
  profiles:
  - name: Home
    state: present
    permanent: true

    allowed_services:
    - ssh
    - cockpit
    - dhcpv6-client
    - mdns
    - samba-client

    allowed_ports:
    - port: 8081
      protocol: tcp
    - port: 8082
      protocol: tcp

    interfaces:
    - bridge0
    - bridge70