---
- name: Deploy the NextCloud Server Container-as-a-Service
  hosts: sukiRemote
  gather_facts: no
  become: yes
  vars:
    caas_name: nextcloud
    service_containers_dir: /opt/caas
    selinux_cheat_codes: false
    update_system: false
    install_podman: false
    create_podman_bridge: false
  tasks:

    - name: Update system
      include_role:
        name: baseLinuxUpdate
      vars:
        reboot_after_kernel_update: false
      when: update_system|bool

    - name: Install Podman
      include_role:
        name: podmanInstall
      when: install_podman|bool

    - name: Create Container Network Bridge
      include_role:
        name: podmanBridgeNet
      when: create_podman_bridge|bool

    - name: Set SELinux Contexts for Container-as-a-Service
      include_role:
        name: caasSELinux
      when: selinux_cheat_codes|bool

    - name: Create Service Containers Directory
      ansible.builtin.file:
        path: "{{ service_containers_dir }}"
        state: directory
        owner: root
        group: root

    - name: Create CaaS Directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: root
        group: root
      with_items:
        - "{{ service_containers_dir }}/{{ caas_name }}"
        - "{{ service_containers_dir }}/{{ caas_name }}/config"
        - "{{ service_containers_dir }}/{{ caas_name }}/volumes"
        - "{{ service_containers_dir }}/{{ caas_name }}/volumes/db_data"
        - "{{ service_containers_dir }}/{{ caas_name }}/volumes/redis_data"
        - "{{ service_containers_dir }}/{{ caas_name }}/volumes/nextcloud"
        - "{{ service_containers_dir }}/{{ caas_name }}/volumes/apps"
        - "{{ service_containers_dir }}/{{ caas_name }}/volumes/config"
        - "{{ service_containers_dir }}/{{ caas_name }}/volumes/data"
        - "/mnt/primary/nfs/nextcloud/data"
        - "{{ service_containers_dir }}/{{ caas_name }}/volumes/config-root"
        - "{{ service_containers_dir }}/{{ caas_name }}/volumes/config-root/etc"
        - "{{ service_containers_dir }}/{{ caas_name }}/volumes/config-root/etc/apache2"
        - "{{ service_containers_dir }}/{{ caas_name }}/volumes/config-root/etc/apache2/conf-enabled"
        - "{{ service_containers_dir }}/{{ caas_name }}/volumes/config-root/usr"
        - "{{ service_containers_dir }}/{{ caas_name }}/volumes/config-root/usr/local"
        - "{{ service_containers_dir }}/{{ caas_name }}/volumes/config-root/usr/local/etc"
        - "{{ service_containers_dir }}/{{ caas_name }}/volumes/config-root/usr/local/etc/php"
        - "{{ service_containers_dir }}/{{ caas_name }}/volumes/config-root/usr/local/etc/php/conf.d"

    - name: Download CaaS deployment files
      copy:
        src: "../containers-as-a-service/caas-{{ item }}"
        dest: "{{ service_containers_dir }}/{{ item }}"
        owner: root
        group: root
      with_items:
        - "{{ caas_name }}/config/service_start.sh"
        - "{{ caas_name }}/config/service_stop.sh"
        - "{{ caas_name }}/config/service_vars.sh"

    - name: Copy Caas Config files
      copy:
        src: "../containers-as-a-service/caas-nextcloud/volumes/config-root/{{ item }}"
        dest: "{{ service_containers_dir }}/{{ caas_name }}/volumes/config-root/{{ item }}"
        owner: root
        group: root
        mode: 0777
      with_items:
        - "usr/local/etc/php/conf.d/nextcloud.ini"
        - "etc/apache2/apache2.conf"
        - "etc/apache2/conf-enabled/security.conf"

    - name: Set executable bit on service bash files
      ansible.builtin.file:
        path: "{{ service_containers_dir }}/{{ item }}"
        mode: 0755
      with_items:
        - "{{ caas_name }}/config/service_start.sh"
        - "{{ caas_name }}/config/service_stop.sh"
        - "{{ caas_name }}/config/service_vars.sh"

    - name: Download CaaS service
      copy:
        src: "../containers-as-a-service/caas-{{ caas_name }}/caas-{{ caas_name }}.service"
        dest: "/etc/systemd/system/caas-{{ caas_name }}.service"
        owner: root
        group: root
        mode: 0755

    - name: Reload systemd
      ansible.builtin.systemd:
        daemon_reload: yes

    - name: Pre-pull the images
      shell: "podman pull {{ container_item }}"
      loop:
        - quay.io/bitnami/redis:latest
        - quay.io/bitnami/postgresql:latest
        - nextcloud
      loop_control:
        loop_var: container_item

    - name: Start CaaS
      ansible.builtin.service:
        name: "caas-{{ caas_name }}"
        state: restarted
        enabled: yes