# podman build -t squid-proxy -f Containerfile .
# podman tag squid-proxy quay.io/kenmoini/squid-proxy:latest
# podman tag squid-proxy quay.io/kenmoini/squid-proxy:$(date +'%F')
# podman push quay.io/kenmoini/squid-proxy:latest
# podman push quay.io/kenmoini/squid-proxy:$(date +'%F')

FROM registry.access.redhat.com/ubi8/ubi:8.6-855

RUN dnf update -y \
 && dnf install -y squid openssl \
 && dnf clean all \
 && rm -rf /var/cache/yum

COPY container_root/ /

RUN update-ca-trust \
 && /usr/sbin/squid -k parse -f /etc/squid.conf

EXPOSE 3128
EXPOSE 3129

CMD /start.sh