---
- name: Create Service Containers Directory
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
  with_items:
    - "{{ container_root_dir }}"
    - "{{ container_root_dir }}/{{ chronyd_service_name }}"
    - "{{ container_root_dir }}/{{ chronyd_service_name }}/scripts"
    - "{{ container_root_dir }}/{{ chronyd_service_name }}/config"

- name: Template CaaS deployment files - servicectl.sh.j2
  ansible.builtin.template:
    src: servicectl.sh.j2
    dest: "{{ container_root_dir }}/{{ chronyd_service_name }}/scripts/servicectl.sh"
    owner: root
    group: root
    mode: 0755

- name: "Template CaaS deployment files - {{ chronyd_service_name }}.service"
  ansible.builtin.template:
    src: service.j2
    dest: "/etc/systemd/system/{{ chronyd_service_name }}.service"
    owner: root
    group: root
    mode: 0755

- name: "Template CaaS deployment files - chrony.conf"
  ansible.builtin.template:
    src: chrony.conf.j2
    dest: "{{ container_root_dir }}/{{ chronyd_service_name }}/config/chrony.conf"
    owner: root
    group: root
    mode: 0755

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Pre-pull the image
  containers.podman.podman_image:
    name: "{{ chronyd_container_image }}"
    pull: yes
    force: yes

- name: Start CaaS
  ansible.builtin.service:
    name: "{{ chronyd_service_name }}"
    state: restarted
    enabled: yes