---
# tasks file for nginxpm
- name: Create Service Containers Directory
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
  with_items:
    - "{{ container_root_dir }}"
    - "{{ container_root_dir }}/{{ npm_service_name }}"
    - "{{ container_root_dir }}/{{ npm_service_name }}/scripts"
    - "{{ container_root_dir }}/{{ npm_service_name }}/volumes"
    - "{{ container_root_dir }}/{{ npm_service_name }}/volumes/certs"
    - "{{ container_root_dir }}/{{ npm_service_name }}/volumes/npm-data"
    - "{{ container_root_dir }}/{{ npm_service_name }}/volumes/db-data"

- name: Template CaaS deployment files - servicectl.sh.j2
  ansible.builtin.template:
    src: servicectl.sh.j2
    dest: "{{ container_root_dir }}/{{ npm_service_name }}/scripts/servicectl.sh"
    owner: root
    group: root
    mode: 0755

- name: "Template CaaS deployment files - {{ npm_service_name }}.service"
  ansible.builtin.template:
    src: service.j2
    dest: "/etc/systemd/system/{{ npm_service_name }}.service"
    owner: root
    group: root
    mode: 0755

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Pre-pull the images
  containers.podman.podman_image:
    name: "{{ image_item }}"
    pull: yes
    force: yes
  loop:
    - "{{ npm_container_image }}"
    - "{{ db_container_image }}"
  loop_control:
    loop_var: image_item

- name: Start CaaS
  ansible.builtin.service:
    name: "{{ npm_service_name }}"
    state: restarted
    enabled: yes