---
# tasks file for shared_pod_stepca

- name: Create Service Containers Directory
  ansible.builtin.file:
    path: "{{ i_path }}"
    state: directory
    owner: root
    group: root
  loop:
    - "{{ container_root_dir }}"
    - "{{ container_root_dir }}/{{ shared_pod_name }}-{{ stepca_service_name }}"
    - "{{ container_root_dir }}/{{ shared_pod_name }}-{{ stepca_service_name }}/volumes/"
  loop_control:
    loop_var: i_path

- name: Create Service Containers Directory - Owned by step user
  ansible.builtin.file:
    path: "{{ i_path }}"
    state: directory
    owner: 1000
    group: 1000
  loop:
    - "{{ container_root_dir }}/{{ shared_pod_name }}-{{ stepca_service_name }}/volumes/step-home"
    - "{{ container_root_dir }}/{{ shared_pod_name }}-{{ stepca_service_name }}/volumes/step-home/config"
  loop_control:
    loop_var: i_path

- name: Template Shared Pod deployment files - containerctl.j2
  ansible.builtin.template:
    src: containerctl.j2
    dest: "{{ container_root_dir }}/{{ shared_pod_name }}/scripts/containers/{{ stepca_service_name }}.sh"
    owner: root
    group: root
    mode: 0755

- name: Template Shared Pod Images
  ansible.builtin.template:
    src: images
    dest: "{{ container_root_dir }}/{{ shared_pod_name }}/scripts/images/{{ stepca_service_name }}"
    owner: root
    group: root
    mode: 0755

- name: Touch a file for the ports for StepCA
  ansible.builtin.file:
    path: "{{ container_root_dir }}/{{ shared_pod_name }}/scripts/ports/{{ i_port }}"
    state: touch
    owner: root
    group: root
  loop:
    - "{{ stepca_container_port }}-tcp"
  loop_control:
    loop_var: i_port

#- name: Template StepCA config
#  ansible.builtin.template:
#    src: "{{ i_file }}.j2"
#    dest: "{{ container_root_dir }}/{{ shared_pod_name }}-{{ stepca_service_name }}/volumes/step-home/config/{{ i_file }}"
#    owner: 1000
#    group: 1000
#    mode: 0644
#  loop:
#    - "defaults.json"
#    - "ca.json"
#  loop_control:
#    loop_var: i_file

- name: Pre-pull the image
  containers.podman.podman_image:
    name: "{{ i_image }}"
    pull: yes
    force: yes
  loop:
    - "{{ stepca_container_image }}"
  loop_control:
    loop_var: i_image

- name: Restart Shared Pod
  ansible.builtin.shell:
    cmd: "{{ container_root_dir }}/{{ shared_pod_name }}/scripts/containers/{{ stepca_service_name }}.sh restart"