---

set_hostname: true
add_root_ca_certs: true

configured_roles:
- update-system # optional reboot if kernel is updated
- install-base-packages
- general-config
- configure-cockpit
- configure-nfs-mounts
- configure-ntp
- configure-sshd
- kvm-host
- podman-host
- setup-ipa-client # optional reboot if newly joined to domain
- configure-firewall