---
# tasks file for freeipa

- name: Create Service Containers Directory
  ansible.builtin.file:
    path: "{{ d_item }}"
    state: directory
    owner: root
    group: root
  loop:
    - "{{ container_root_dir }}"
    - "{{ container_root_dir }}/{{ freeipa_service_name }}"
    - "{{ container_root_dir }}/{{ freeipa_service_name }}/scripts"
    - "{{ container_root_dir }}/{{ freeipa_service_name }}/volumes"
    - "{{ container_root_dir }}/{{ freeipa_service_name }}/volumes/data"
  loop_control:
    loop_var: d_item

- name: Template CaaS deployment files - servicectl.sh.j2
  ansible.builtin.template:
    src: servicectl.sh.j2
    dest: "{{ container_root_dir }}/{{ freeipa_service_name }}/scripts/servicectl.sh"
    owner: root
    group: root
    mode: 0755

- name: "Template CaaS deployment files - {{ freeipa_service_name }}.service"
  ansible.builtin.template:
    src: service.j2
    dest: "/etc/systemd/system/{{ freeipa_service_name }}.service"
    owner: root
    group: root
    mode: 0755

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Pre-pull the image
  containers.podman.podman_image:
    name: "{{ freeipa_container_image }}"
    pull: yes
    force: yes

- name: Start CaaS
  ansible.builtin.service:
    name: "{{ freeipa_service_name }}"
    state: restarted
    enabled: yes

- name: Display helper text
  ansible.builtin.debug:
    msg:
      - By default the service will not start - you will need to initialize it first. Do so by running:"
      - "{{ container_root_dir }}/{{ freeipa_service_name }}/scripts/servicectl.sh init"