AUTHENTICATION_TYPE: LDAP
AVATAR_KIND: local
BITTORRENT_FILENAME_PEPPER: 47809e76-833e-4898-86f2-2af31767f7ac
BUILDLOGS_REDIS:
    host: redis-quay
    password: s0m3Str0ngP455w0rd
    port: 6379
CONTACT_INFO:
    - https://kenmoini.com
    - mailto:ken@kenmoini.com
DATABASE_SECRET_KEY: 13236f1d-3d2d-4cb8-b9da-0feee025e99d
DB_CONNECTION_ARGS: {}
DB_URI: postgresql://quaypgu:somethingS3cr3t@postgresql-quay/quay
DEFAULT_TAG_EXPIRATION: 2w
DISTRIBUTED_STORAGE_CONFIG:
    default:
        - RHOCSStorage
        - access_key: AKIAIOSFODNN71337HAX
          bucket_name: quay
          hostname: minio-quay
          is_secure: false
          port: "9000"
          secret_key: wJalrXUtnFEMI/K7MDENG/bPxRfiCY1337HAXKEY
          storage_path: /datastorage/registry
DISTRIBUTED_STORAGE_DEFAULT_LOCATIONS: []
DISTRIBUTED_STORAGE_PREFERENCE:
    - default
ENTERPRISE_LOGO_URL: https://polyglot.ventures/img/polyglotLR.png
FEATURE_ACI_CONVERSION: false
FEATURE_ACTION_LOG_ROTATION: false
FEATURE_ANONYMOUS_ACCESS: true
FEATURE_APP_REGISTRY: false
FEATURE_APP_SPECIFIC_TOKENS: true
FEATURE_BITBUCKET_BUILD: false
FEATURE_BLACKLISTED_EMAILS: false
FEATURE_BUILD_SUPPORT: false
FEATURE_CHANGE_TAG_EXPIRATION: true
FEATURE_DIRECT_LOGIN: true
FEATURE_FIPS: false
FEATURE_GITHUB_BUILD: false
FEATURE_GITHUB_LOGIN: false
FEATURE_GITLAB_BUILD: false
FEATURE_GOOGLE_LOGIN: false
FEATURE_INVITE_ONLY_USER_CREATION: false
FEATURE_MAILING: false
FEATURE_NONSUPERUSER_TEAM_SYNCING_SETUP: false
FEATURE_PARTIAL_USER_AUTOCOMPLETE: true
FEATURE_PROXY_STORAGE: false
FEATURE_REPO_MIRROR: true
FEATURE_REQUIRE_TEAM_INVITE: true
FEATURE_RESTRICTED_V1_PUSH: true
FEATURE_SECURITY_NOTIFICATIONS: false
FEATURE_SECURITY_SCANNER: false
FEATURE_SIGNING: false
FEATURE_STORAGE_REPLICATION: false
FEATURE_TEAM_SYNCING: false
FEATURE_USER_CREATION: true
FEATURE_USER_LAST_ACCESSED: true
FEATURE_USER_LOG_ACCESS: false
FEATURE_USER_METADATA: false
FEATURE_USER_RENAME: false
FEATURE_USERNAME_CONFIRMATION: true
FRESH_LOGIN_TIMEOUT: 10m
GITHUB_LOGIN_CONFIG: {}
GITHUB_TRIGGER_CONFIG:
    API_ENDPOINT: https://api.github.com/
    GITHUB_ENDPOINT: https://github.com/
GITLAB_TRIGGER_KIND: {}
GPG2_PRIVATE_KEY_FILENAME: signing-private.gpg
GPG2_PUBLIC_KEY_FILENAME: signing-public.gpg
LDAP_ADMIN_DN: uid=admin,cn=users,cn=accounts,dc=kemo,dc=labs
LDAP_ADMIN_PASSWD: s0m3P455
LDAP_ALLOW_INSECURE_FALLBACK: false
LDAP_BASE_DN:
    - dc=kemo
    - dc=labs
LDAP_EMAIL_ATTR: mail
LDAP_UID_ATTR: uid
LDAP_URI: ldaps://idm.kemo.labs:636
LDAP_USER_RDN:
    - cn=users
    - cn=accounts
LOG_ARCHIVE_LOCATION: default
LOGS_MODEL: database
LOGS_MODEL_CONFIG: {}
MAIL_DEFAULT_SENDER: support@quay.io
MAIL_PORT: 587
MAIL_USE_AUTH: false
MAIL_USE_TLS: false
PREFERRED_URL_SCHEME: http
REGISTRY_TITLE: Kemo Labs Quay Container Registry
REGISTRY_TITLE_SHORT: Quay
REPO_MIRROR_INTERVAL: 30
REPO_MIRROR_TLS_VERIFY: false
SEARCH_MAX_RESULT_PAGE_COUNT: 10
SEARCH_RESULTS_PER_PAGE: 10
SECRET_KEY: 3b39cb73-a722-4264-84de-c3f2e764e365
SECURITY_SCANNER_INDEXING_INTERVAL: 30
SECURITY_SCANNER_V4_ENDPOINT: http://clair-quay
SECURITY_SCANNER_V4_PSK: MzZmOGM4YWpjYWlhOQ==
SERVER_HOSTNAME: quay.kemo.labs
SETUP_COMPLETE: true
SUPER_USERS:
    - quayadmin
    - kemo
TAG_EXPIRATION_OPTIONS:
    - 0s
    - 1d
    - 1w
    - 2w
    - 4w
TEAM_RESYNC_STALE_TIME: 30m
TESTING: false
USE_CDN: false
USER_EVENTS_REDIS:
    host: redis-quay
    password: s0m3Str0ngP455w0rd
    port: 6379
USER_RECOVERY_TOKEN_LIFETIME: 30m
USERFILES_LOCATION: default
