---
- name: Update system
  ansible.builtin.apt:
    name: "*"
    state: latest
    update_cache: yes
  register: yum_updates

- name: server update reboot | Check if reboot is needed because kernel was upgraded
  ansible.builtin.shell: LAST_KERNEL=$(rpm -q --last kernel | awk 'NR==1{sub(/kernel-/,""); print $1}'); CURRENT_KERNEL=$(uname -r); if [ $LAST_KERNEL != $CURRENT_KERNEL ]; then echo 'reboot'; else echo 'no'; fi # noqa 204 306
  register: yum_reboot_hint_result
  changed_when: false

- name: set_fact for reboot
  when: yum_reboot_hint_result.stdout.find("no") != -1
  ansible.builtin.set_fact:
    reboot_hint_result: false

- name: set_fact for reboot
  when: yum_reboot_hint_result.stdout.find("reboot") != -1
  ansible.builtin.set_fact:
    reboot_hint_result: true

- name: Reboot if needed
  when: reboot_hint_result|bool and reboot_after_kernel_update|bool
  ansible.builtin.reboot:
    reboot_timeout: "{{ reboot_wait_timeout }}"