---
# tasks file for shared_db_pgsql

- name: Create Service Containers Directory
  ansible.builtin.file:
    path: "{{ i_path }}"
    state: directory
    owner: root
    group: root
  loop:
    - "{{ container_root_dir }}"
    - "{{ container_root_dir }}/{{ shared_pod_name }}-{{ pgsql_service_name }}"
    - "{{ container_root_dir }}/{{ shared_pod_name }}-{{ pgsql_service_name }}/volumes/"
    - "{{ container_root_dir }}/{{ shared_pod_name }}-{{ pgsql_service_name }}/volumes/secrets"
  loop_control:
    loop_var: i_path

- name: Create Service Containers - Postgresql Directory
  ansible.builtin.file:
    path: "{{ i_path }}"
    state: directory
    owner: 70
    group: 70
  loop:
    - "{{ container_root_dir }}/{{ shared_pod_name }}-{{ pgsql_service_name }}/volumes/db-data"
  loop_control:
    loop_var: i_path

- name: Create Service Containers - PGAdmin Directory
  ansible.builtin.file:
    path: "{{ i_path }}"
    state: directory
    owner: 5050
    group: 5050
  loop:
    - "{{ container_root_dir }}/{{ shared_pod_name }}-{{ pgsql_service_name }}/volumes/pgadmin"
  loop_control:
    loop_var: i_path

- name: Template Postgresql Config File
  ansible.builtin.template:
    src: postgresql.conf.j2
    dest: "{{ container_root_dir }}/{{ shared_pod_name }}-{{ pgsql_service_name }}/volumes/postgresql.conf"
    owner: root
    group: root
    mode: 0755

- name: Template Postgresql DB Env file
  ansible.builtin.template:
    src: env.db.j2
    dest: "{{ container_root_dir }}/{{ shared_pod_name }}-{{ pgsql_service_name }}/volumes/secrets/env.db"
    owner: root
    group: root
    mode: 0755

- name: Template Shared Pod deployment files - containerctl.j2
  ansible.builtin.template:
    src: containerctl.j2
    dest: "{{ container_root_dir }}/{{ shared_pod_name }}/scripts/containers/{{ pgsql_service_name }}.sh"
    owner: root
    group: root
    mode: 0755

- name: Template Shared Pod Images
  ansible.builtin.template:
    src: images
    dest: "{{ container_root_dir }}/{{ shared_pod_name }}/scripts/images/{{ pgsql_service_name }}"
    owner: root
    group: root
    mode: 0755

- name: Touch a file for the container ports
  ansible.builtin.file:
    path: "{{ container_root_dir }}/{{ shared_pod_name }}/scripts/ports/{{ i_port }}"
    state: touch
    owner: root
    group: root
  loop:
    - "{{ pgadmin_container_port }}-tcp"
    - "{{ pgsql_db_port }}-tcp"
  loop_control:
    loop_var: i_port

- name: Pre-pull the image
  containers.podman.podman_image:
    name: "{{ i_image }}"
    pull: yes
    force: yes
  loop:
    - "{{ pgadmin_container_image }}"
    - "{{ pgsql_db_container_image }}"
  loop_control:
    loop_var: i_image

- name: Restart Shared Pod
  ansible.builtin.shell:
    cmd: "{{ container_root_dir }}/{{ shared_pod_name }}/scripts/containers/{{ pgsql_service_name }}.sh restart"