apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-unreal-engine
spec:
  workspaces:
  - name: ue-workspace
  params:
  - name: git-url
    type: string
    description: url of the git repo for the code of deployment
  - name: git-revision
    type: string
    description: revision to be used from repo of the code for deployment
    default: "4.25-pixel-streaming"
  tasks:
  - name: fetch-repository
    taskRef:
      name: git-clone
      kind: ClusterTask
    workspaces:
    - name: output
      workspace: ue-workspace
    params:
    - name: url
      value: $(params.git-url)
    - name: revision
      value: $(params.git-revision)
    - name: subdirectory
      value: ""
    - name: submodules
      value: 'true'
    - name: depth
      value: '1'
    - name: sslVerify
      value: 'false'
    - name: deleteExisting
      value: 'true'
    - name: verbose
      value: 'true'