---
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: pull-mono-deps-taskrun
spec:
  taskRef:
    name: pull-mono-deps-task
  podTemplate:
    volumes:
    - name: mono-cache
      persistentVolumeClaim:
        claimName: mono-cache-pvc
  resources:
    inputs:
      - name: source
        resourceRef:
          name: ue-git-resource