---
# tasks file for configure-nfs-mounts
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Ensure NFS packages are installed.
  ansible.builtin.package:
    name: "{{ nfs_packages }}"
    state: present

- name: Mount the NFS Shares
  ansible.builtin.mount:
    src: "{{ mount_item.src }}"
    path: "{{ mount_item.path }}"
    fstype: nfs
    opts: "vers={{ nfs_version }},{{ mount_item.opts | default(nfs_mount_opts) }}"
    dump: "{{ mount_item.dump | default(omit) }}"
    passno: "{{ mount_item.passno | default(omit) }}"
    state: "{{ mount_item.state | default( 'mounted' ) }}"
    boot: "{{ mount_item.boot | default(true) }}"
  loop: "{{ nfs_mounts }}"
  loop_control:
    loop_var: mount_item