global:
  scrape_interval: 10s
  scrape_timeout: 5s
  evaluation_interval: 15s
alerting:
  alertmanagers:
  - static_configs:
    - targets: []
    scheme: http
    timeout: 10s
    api_version: v1
scrape_configs:
- job_name: prometheus
  static_configs:
  - targets: ['localhost:9090']
- job_name: nodeExporter
  static_configs:
  - targets: ['raza.kemo.labs:9100']
  - targets: ['suki.kemo.labs:9100']
  - targets: ['endurance.kemo.labs:9100']