---
# FROM https://github.com/kylemanna/docker-openvpn
- name: Deploy the caas-openvpn Container-as-a-Service
  hosts: containerHost
  gather_facts: yes
  become: yes
  vars:
    caas_name: caas-openvpn
    service_containers_dir: /opt/service-containers
    selinux_cheat_codes: false
  tasks:

    - name: Update system
      include_role:
        name: baseLinuxUpdate
      vars:
        reboot_after_kernel_update: false

    - name: Install Podman
      include_role:
        name: podmanInstall

    - name: Create Container Network Bridge
      include_role:
        name: podmanBridgeNet

    - name: Set SELinux Contexts for Container-as-a-Service
      include_role:
        name: caasSELinux
      when: selinux_cheat_codes|bool

    - name: Create Service Containers Directory
      ansible.builtin.file:
        path: "{{ service_containers_dir }}"
        state: directory
        owner: root
        group: root

    - name: Create CaaS Directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: root
        group: root
      with_items:
        - "{{ service_containers_dir }}/{{ caas_name }}"
        - "{{ service_containers_dir }}/{{ caas_name }}/config"
        - "{{ service_containers_dir }}/{{ caas_name }}/volumes"
        - "{{ service_containers_dir }}/{{ caas_name }}/volumes/etc-conf"

    - name: Download CaaS deployment files
      copy:
        src: "../containers-as-a-service/{{ item }}"
        dest: "{{ service_containers_dir }}/{{ item }}"
        owner: root
        group: root
      with_items:
        - "{{ caas_name }}/config/service_start.sh"
        - "{{ caas_name }}/config/service_stop.sh"
        - "{{ caas_name }}/config/service_vars.sh"
        - "{{ caas_name }}/volumes/etc-conf/openvpn.conf"
        - "{{ caas_name }}/volumes/etc-conf/ovpn_env.sh"

    - name: Set executable bit on service bash files
      ansible.builtin.file:
        path: "{{ service_containers_dir }}/{{ item }}"
        mode: 0755
      with_items:
        - "{{ caas_name }}/config/service_start.sh"
        - "{{ caas_name }}/config/service_stop.sh"
        - "{{ caas_name }}/config/service_vars.sh"

    - name: Download CaaS service
      copy:
        src: "../containers-as-a-service/{{ caas_name }}/{{ caas_name }}.service"
        dest: "/etc/systemd/system/{{ caas_name }}.service"
        owner: root
        group: root
        mode: 0755

    - name: Check for PKI files
      stat:
        path: "{{ service_containers_dir }}/{{ caas_name }}/volumes/etc-conf/pki/dh.pem"
      register: pki_check

    - name: Fail if PKI is missing
      fail:
        msg: "PKI Missing!  Run 'podman run -v {{ service_containers_dir }}/{{ caas_name }}/volumes/etc-conf:/etc/openvpn --rm -it kylemanna/openvpn ovpn_initpki nopass' on the container host first!"
      when: not pki_check.stat.exists

    - name: Reload systemd
      ansible.builtin.systemd:
        daemon_reload: yes

    - name: Pre-pull the image
      shell: podman pull kylemanna/openvpn:latest

    - name: Start CaaS
      ansible.builtin.service:
        name: "{{ caas_name }}"
        state: restarted
        enabled: yes

    - name: Create a new user
      debug:
        msg: "podman run -v {{ service_containers_dir }}/{{ caas_name }}/volumes/etc-conf:/etc/openvpn --rm -it kylemanna/openvpn easyrsa build-client-full CLIENTNAME nopass"

    - name: Download user cert+config
      debug:
        msg: "podman run -v {{ service_containers_dir }}/{{ caas_name }}/volumes/etc-conf:/etc/openvpn --rm -it kylemanna/openvpn ovpn_getclient CLIENTNAME > CLIENTNAME.ovpn"