---
- name: Deploy the NFS Server Container-as-a-Service
  hosts: suki
  gather_facts: yes
  become: yes
  vars:
    caas_name: nfs
    service_containers_dir: /mnt/fastAndLoose/caas
    selinux_cheat_codes: false
    update_system: false
    install_podman: false
    create_podman_bridge: false
  tasks:

    - name: Update system
      include_role:
        name: baseLinuxUpdate
      vars:
        reboot_after_kernel_update: false
      when: update_system|bool

    - name: Install Podman
      include_role:
        name: podmanInstall
      when: install_podman|bool

    - name: Create Container Network Bridge
      include_role:
        name: podmanBridgeNet
      when: create_podman_bridge|bool

    - name: Set SELinux Contexts for Container-as-a-Service
      include_role:
        name: caasSELinux
      when: selinux_cheat_codes|bool

    - name: Create Service Containers Directory
      ansible.builtin.file:
        path: "{{ service_containers_dir }}"
        state: directory
        owner: root
        group: root

    - name: Create CaaS Directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: root
        group: root
      with_items:
        - "{{ service_containers_dir }}/{{ caas_name }}"
        - "{{ service_containers_dir }}/{{ caas_name }}/config"
        - "{{ service_containers_dir }}/{{ caas_name }}/volumes"
        - "{{ service_containers_dir }}/{{ caas_name }}/volumes/etc-conf"

    - name: Create NFS Directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: root
        group: root
        mode: 0777
      with_items:
        - "/mnt/fastAndLoose/nfs/old/ocp"
        - "/mnt/fastAndLoose/nfs/old/ocpreg"
        - "/mnt/fastAndLoose/nfs/old/vms"
        - "/mnt/fastAndLoose/nfs/old/isos"
        - "/mnt/fastAndLoose/nfs/old/vmgr"
        - "/mnt/fastAndLoose/nfs/old/dropbox"
        - "/mnt/fastAndLoose/nfs/old/nrs_dropbox"
        - "/mnt/fastAndLoose/nfs/ocp"
        - "/mnt/fastAndLoose/nfs/ocpreg"
        - "/mnt/fastAndLoose/nfs/ocp/core-ocp"
        - "/mnt/fastAndLoose/nfs/ocpreg/core-ocp"
        - "/mnt/fastAndLoose/nfs/grafana"
        - "/mnt/fastAndLoose/nfs/nextcloud"
        - "/mnt/fastAndLoose/nfs/media"
        - "/mnt/fastAndLoose/nfs/plex"
        - "/mnt/fastAndLoose/nfs/radarr"
        - "/mnt/fastAndLoose/nfs/sonarr"
        - "/mnt/fastAndLoose/nfs/isos"
        - "/mnt/fastAndLoose/nfs/vms"
        - "/mnt/fastAndLoose/nfs/vms/raza"
        - "/mnt/fastAndLoose/nfs/vms/suki"

    - name: Download CaaS deployment files
      copy:
        src: "../containers-as-a-service/caas-{{ item }}"
        dest: "{{ service_containers_dir }}/{{ item }}"
        owner: root
        group: root
      with_items:
        - "{{ caas_name }}/config/service_start.sh"
        - "{{ caas_name }}/config/service_stop.sh"
        - "{{ caas_name }}/config/service_vars.sh"
        - "{{ caas_name }}/volumes/etc-conf/exports"

    - name: Set executable bit on service bash files
      ansible.builtin.file:
        path: "{{ service_containers_dir }}/{{ item }}"
        mode: 0755
      with_items:
        - "{{ caas_name }}/config/service_start.sh"
        - "{{ caas_name }}/config/service_stop.sh"
        - "{{ caas_name }}/config/service_vars.sh"

    - name: Download CaaS service
      copy:
        src: "../containers-as-a-service/caas-{{ caas_name }}/caas-{{ caas_name }}.service"
        dest: "/etc/systemd/system/caas-{{ caas_name }}.service"
        owner: root
        group: root
        mode: 0755

    - name: Add kernel module loader for nfs
      ansible.builtin.copy:
        content: 'nfs'
        dest: /etc/modules-load.d/nfs.conf

    - name: Add kernel module loader for nfsd
      ansible.builtin.copy:
        content: 'nfsd'
        dest: /etc/modules-load.d/nfsd.conf

    - name: Run modprobe now to immediately enable
      shell: "modprobe {{ item }}"
      loop:
        - nfs
        - nfsd

    - name: Reload systemd
      ansible.builtin.systemd:
        daemon_reload: yes

    - name: Pre-pull the image
      shell: podman pull erichough/nfs-server

    - name: Start CaaS
      ansible.builtin.service:
        name: "caas-{{ caas_name }}"
        state: restarted
        enabled: yes