---
- name: Deploy the Homelab Metrics Node Exporter Container-as-a-Service
  hosts: containerHosts
  gather_facts: yes
  become: yes
  vars:
    caas_name: metrics-node-exporter
    service_containers_dir: /opt/service-containers
    selinux_cheat_codes: false
    update_system: true
    install_podman: false
    create_podman_bridge: false
  tasks:

    - name: Update system
      include_role:
        name: baseLinuxUpdate
      vars:
        reboot_after_kernel_update: false
      when: update_system|bool

    - name: Install Podman
      include_role:
        name: podmanInstall
      when: install_podman|bool

    - name: Create Container Network Bridge
      include_role:
        name: podmanBridgeNet
      when: create_podman_bridge|bool

    - name: Set SELinux Contexts for Container-as-a-Service
      include_role:
        name: caasSELinux
      when: selinux_cheat_codes|bool

    - name: Create Service Containers Directory
      ansible.builtin.file:
        path: "{{ service_containers_dir }}"
        state: directory
        owner: root
        group: root

    - name: Create CaaS Directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: root
        group: root
      with_items:
        - "{{ service_containers_dir }}/{{ caas_name }}"
        - "{{ service_containers_dir }}/{{ caas_name }}/scripts"

    - name: Download CaaS deployment files
      copy:
        src: "../containers-as-a-service/caas-{{ item }}"
        dest: "{{ service_containers_dir }}/{{ item }}"
        owner: root
        group: root
        mode: 0755
      with_items:
        - "{{ caas_name }}/scripts/service_start.sh"
        - "{{ caas_name }}/scripts/service_stop.sh"
        - "{{ caas_name }}/scripts/service_vars.sh"

    - name: Download CaaS service
      copy:
        src: "../containers-as-a-service/caas-{{ caas_name }}/caas-{{ caas_name }}.service"
        dest: "/etc/systemd/system/caas-{{ caas_name }}.service"
        owner: root
        group: root
        mode: 0755

    - name: Reload systemd
      ansible.builtin.systemd:
        daemon_reload: yes

    - name: Pre-pull the images
      shell: "podman pull {{ container_item }}"
      loop:
        - quay.io/prometheus/node-exporter:latest
      loop_control:
        loop_var: container_item

    - name: Start CaaS
      ansible.builtin.service:
        name: "caas-{{ caas_name }}"
        state: restarted
        enabled: yes