apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: nfd
  namespace: openshift-operators 
spec:
  channel: '4.7'
  installPlanApproval: Automatic
  name: nfd
  source: redhat-operators 
  sourceNamespace: openshift-marketplace 