---
- name: Create Service Containers Directory
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
  with_items:
    - "{{ container_root_dir }}"
    - "{{ container_root_dir }}/pdns"
    - "{{ container_root_dir }}/pdns/scripts"
    - "{{ container_root_dir }}/pdns/volumes"
    - "{{ container_root_dir }}/pdns/volumes/mysql"
    - "{{ container_root_dir }}/pdns/volumes/web-ui"

- name: Create Service Containers Directory
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: 27
    group: 27
  with_items:
    - "{{ container_root_dir }}/pdns/volumes/mysql"
    - "{{ container_root_dir }}/pdns/volumes/web-ui"

- name: Create Service Containers Directory
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: 100
    group: 101
  with_items:
    - "{{ container_root_dir }}/pdns/volumes/web-ui"

- name: Template CaaS deployment files - servicectl.sh.j2
  ansible.builtin.template:
    src: pdns/servicectl.sh.j2
    dest: "{{ container_root_dir }}/pdns/scripts/servicectl.sh"
    owner: root
    group: root
    mode: 0755

- name: "Template CaaS deployment files - pdns.service"
  ansible.builtin.template:
    src: pdns/service.j2
    dest: "/etc/systemd/system/pdns.service"
    owner: root
    group: root

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Pre-pull the images
  containers.podman.podman_image:
    name: "{{ ctnr_item }}"
    pull: yes
    force: yes
    auth_file: "{{ ghcr_pull_auth_file | default(omit) }}"
  loop:
    - ghcr.io/kenmoini/lab-powerdns:mysql-latest
    - quay.io/kenmoini/pdns-auth:latest
    - quay.io/kenmoini/pdns-recursor:latest
  loop_control:
    loop_var: ctnr_item